### ISSUE TITLE
how can this be customized for meta quest 2?

### ISSUE THREAD

**Issue by addy1997** [bryik/aframe-ball-throw#11]
Hi @bryik,

This is an amazing project. How can I customize it for Meta Quest 2 headset? Are there any specific commands to be added such as `vive-controls`?

Thanks
adwait

**Comment by bryik** [comment]
Hi @addy1997, this project is fairly old so it won't be straightforward to get it working with Meta Quest 2. It uses A-Frame v1.0.4 which IIRC lacked support for Quest controllers. The next time I have a headset handy, I'll try to update this project to the latest version of A-Frame.

If you're really keen, I think your best bet would be to start from scratch rather than fork this project. Go through [A-Frame's intro docs](https://aframe.io/docs/1.4.0/introduction/), get the basic "hello world" scene working with your Quest 2, then maybe try to [add physics](https://github.com/c-frame/aframe-physics-system).
